name: Deploy to Server

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest frontend/robotic-main
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

    - name: Build and push backend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest backend/
        docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SSH_USER: ${{ secrets.SSH_USER }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts

        ssh $SSH_USER@$SERVER_IP << EOF
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker pull $DOCKER_USERNAME/frontend:latest
          docker pull $DOCKER_USERNAME/backend:latest
          cd /root/robotick
          git checkout dev
          docker-compose down && docker-compose up -d --build
        EOF
